apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohelloworld
  namespace: dev
  labels:
    app: gohelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohelloworld
  template:
    metadata:
      labels:
        app: gohelloworld
    spec:
      containers:
        - name: gohelloworld
          image: 307679855071.dkr.ecr.us-west-2.amazonaws.com/gohelloworld:26
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: gohelloworld
spec:
  selector:
    app: gohelloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
